ligues_platform_forum:
    path:     /MaisonDesLigue-forum
    defaults: { _controller: LIGUESPlatformBundle:Default:forum }

ligues_platform_forum_compte:
    path:     /MaisonDesLigue-forum-compte
    defaults: { _controller: LIGUESPlatformBundle:Default:compte }

ligues_platform_forum_compte_formulaire:
    path:     /MaisonDesLigue-forum-compte-formulaire
    defaults: { _controller: LIGUESPlatformBundle:Default:formulaire_inscription }

ligues_platform_forum_espace_membre:
    path:     /MaisonDesLigue-forum-espace-membre
    defaults: { _controller: LIGUESPlatformBundle:Default:espace_membre }

ligues_platform_forum_espace_membre_categorie_membre:
    path:     /MaisonDesLigue-forum-espace-membre-categorie
    defaults: { _controller: LIGUESPlatformBundle:Default:espace_membre_categorie }

ligues_platform_forum_espace_membre_categorie_foot:
    path:     /MaisonDesLigue-forum-espace-membre-categorie-foot
    defaults: { _controller: LIGUESPlatformBundle:Default:categorie_foot }

ligues_platform_forum_espace_membre_ajouter_article_formulaire:
    path:     /MaisonDesLigue-forum-espace-membre-ajouter-article-formulaire
    defaults: { _controller: LIGUESPlatformBundle:Default:ajouter_article_formulaire }

ligues_platform_forum_espace_membre_ajouter_article_formulaire:
    path:     /MaisonDesLigue-forum-espace-membre-ajouter-article
    defaults: { _controller: LIGUESPlatformBundle:Default:ajouter_article }